services:
    dummy-todo-api:
        build: .
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: production
            DATABASE_URL: postgres://postgres:postgres@postgres:5432/todo_db
        depends_on:
            - postgres

    postgres:
        image: postgres:14
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: todo_db
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
